trigger:
- main

pool:
  mytestpool

jobs:
- job: RunPythonScriptJob
  displayName: 'Run Python Script'
  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      addToPath: true

  - script: python hello.py
    displayName: 'Run Your Python Script'