trigger:
- main

pool:
  mytestpool

jobs:
- job: RunPythonScriptJob
  displayName: 'Run Python Script'
  steps:
  - checkout: self

  - script: |
      sudo add-apt-repository ppa:deadsnakes/ppa -y
      sudo apt-get update
      sudo apt-get install python3.8 -y
    displayName: 'Install Python 3.8'

  - script: |
      echo "export GITHUB_TOKEN=$GITHUB_TOKEN" >> ~/.bashrc
      source ~/.bashrc
      python3.8 hello.py
    displayName: 'Run Your Python Script'
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
