trigger:
- main

pool:
  mytestpool

jobs:
- job: HelloWorldJob
  displayName: 'Hello, World! Build'
  steps:
  - checkout: self

  - script: echo 'Hello, World!'
    displayName: 'Print Hello, World!'
